In [140]:
import numpy as np
import re
import string
from matplotlib import pyplot as plt
import pandas as pd
import os
import unidecode as un
from scipy import spatial
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import matplotlib.pyplot as plt

In [145]:
letters = " abcdefghijklmnopqrstuvwxyz"
s = {}
dimensions = 100
n = 3
a = 27
label = []
train = []
for filename in os.listdir("lang"):
    data = open("lang/" + filename, mode = 'r', encoding="utf8")
    name = filename.split("_", 1)
    label.append(name[0])
    for line in data:
        df = un.unidecode(line).lower()
        
        for x in df:
            if(x not in letters):
                df = df.replace(x, '')

        ngrams = [df[i:i+n] for i in range(len(df)-1)]
        for ngram in ngrams:
            if (s.get(ngram) is None):
                s[ngram] = 1
            else:
                s[ngram] += 1
    train.append(s)
    s = {}


In [146]:
testS = []
s_dict = {}
testingLabels = []
foldr = ["bg", "cs", "da", "de", "el", "en", "es", "et", "fi", "fr", "hu", "it", "lt", "lv", "nl", "pl", "pt", "ro", "sk", "sl" , "sv"]
path = "txt/bg/"
for filename in os.listdir("txt"):
    i = 0
    for file in os.listdir("txt/" + filename):
        if(i < 10):
            data = open("txt/" + filename + "/"+ file, mode = "r", encoding = "utf8")
            for line in data:
                dt = un.unidecode(line).lower()
                for x in dt:
                    if(x not in letters):
                        dt = dt.replace(x, '')
                ngrams = [dt[i:i+n] for i in range(len(dt)-1)]
                for ngram in ngrams:
                    if (s_dict.get(ngram) is None):
                        s_dict[ngram] = 1
                    else:
                        s_dict[ngram] += 1
            testS.append(s_dict)
            testingLabels.append(filename)
            s_dict = {}
            i += 1
        else:
            pass

In [147]:
dictionary = {}

for l in letters:
    dictionary[l] = np.random.choice([-1, 1], size=dimensions)

dictionary

{' ': array([ 1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1,  1,
         1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1,  1,  1, -1, -1,
        -1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1, -1,
         1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,  1,
         1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1,  1, -1,  1,  1,
         1, -1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1]),
 'a': array([-1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1,  1,  1, -1,  1,
         1, -1, -1, -1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,
         1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1,  1,
        -1, -1,  1, -1,  1, -1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,
        -1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1,
        -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1]),
 'b': array([ 1, -1, -1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1,
         

In [153]:
def h(listS):
    listH = []
    for s in listS:
        h = np.zeros(dimensions)       
        for ngram in s.keys():
            n_i = np.random.choice([1], size = dimensions)
            s_i = s[ngram]
            j = 1
            for x in ngram:
                n_i = np.multiply(n_i, np.roll(dictionary[x], j))
                j +=1
            h += s_i * n_i
        h = h/np.linalg.norm(h)
        listH.append(h)
    return(listH)

In [154]:
training_H = h(train) 
testing_H = h(testS)

In [155]:
predLabels = []
for test in testing_H:
    cos = []
    for training in training_H:
        cosine = np.dot(test,training)/(np.linalg.norm(test)*np.linalg.norm(training))
        cos.append(cosine)
    maxIndex = np.argmax(cos)
    predLabels.append(label[maxIndex])
print(predLabels)

['fi', 'bg', 'fi', 'bg', 'fi', 'fi', 'fi', 'bg', 'bg', 'bg', 'en', 'de', 'en', 'fi', 'cs', 'pl', 'en', 'sk', 'fr', 'fi', 'da', 'da', 'da', 'da', 'da', 'da', 'da', 'da', 'da', 'da', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'el', 'el', 'el', 'el', 'el', 'el', 'el', 'el', 'el', 'el', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'es', 'es', 'es', 'es', 'es', 'es', 'es', 'es', 'es', 'es', 'fi', 'et', 'en', 'et', 'et', 'fi', 'fi', 'et', 'et', 'sv', 'fi', 'fi', 'fi', 'fi', 'fi', 'fi', 'fi', 'fi', 'fi', 'fi', 'fr', 'fr', 'fr', 'fr', 'fr', 'fr', 'fr', 'fr', 'fr', 'fr', 'hu', 'hu', 'en', 'en', 'en', 'hu', 'en', 'hu', 'es', 'en', 'it', 'it', 'it', 'it', 'it', 'it', 'it', 'it', 'it', 'it', 'el', 'fr', 'fi', 'pl', 'lv', 'en', 'en', 'lv', 'en', 'fi', 'lv', 'lv', 'lv', 'lv', 'pt', 'lv', 'fi', 'lv', 'lv', 'pl', 'nl', 'nl', 'nl', 'nl', 'nl', 'nl', 'nl', 'nl', 'nl', 'nl', 'pl', 'sv', 'pl', 'pt', 'el', 'sk', 'es', 'pl', 'bg', 'fr', 'pt', 'pt', 'pt', 'pt', 'pt', 'pt', 'pt

In [157]:
right = 0
for each in range(len(predLabels)):
    if(predLabels[each] == testingLabels[each]):
        right +=1
print(right/(len(predLabels)))

0.7


Dimensions: 1000 Accuracy: 0.7952380952380952
Dimensions: 100  Accuracy: 0.7

In [158]:
disp = confusion_matrix(predLabels, testingLabels)
print(disp)
print(f1_score(testingLabels, predLabels, average = "weighted"))

[[ 5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  2  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0]
 [ 0  3  0  0  0 10  0  1  0  0  5  0  3  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0 10  0  0  0  1  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  2  0  0  0  0  0  3 10  0  0  0  2  1  0  0  0  0  0  3  0]
 [ 0  1  0  0  0  0  0  0  0 10  0  0  1  0  0  1  0  1  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0]
 [ 0  1  0